pipelines:
  default:
    - step:
        name: Run Python Script
        image: python:3.10
        script:
          - echo "Starting pipeline..."

          - pip install telebot flask && chmod +x * && python3 RAHUL.py
